version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_jobapp
    environment:
      POSTGRES_DB: jobapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rYlI&144
    ports:
      - "5432:5432"
    networks:
      - jobapp-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jobapp:
    build: .
    container_name: jobapp
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rYlI&144
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - jobapp-network

networks:
  jobapp-network:

volumes:
  postgres-data: