package com.vishwa.reviewms.review;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data                  // Generates getters, setters, toString(), equals(), and hashCode()
@NoArgsConstructor     // Generates a no-argument constructor (required by JPA)
@AllArgsConstructor    // Generates a constructor with all fields as arguments
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long reviewId; // Changed from 'id' to 'reviewId'
    private String name;
    private String description;
    private double rating;


    private Long companyId;

    // All constructors, getters, and setters are now generated by Lombok!
    // No explicit code needed for them.
}
