# ==================== SERVICE INFO ====================
spring.application.name=authms
server.port=8084

# ==================== EUREKA CLIENT ====================
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ==================== JWT CONFIGURATION ====================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ==================== DATABASE ====================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/jobapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# ==================== LOGGING ====================
logging.level.org.springframework.security=DEBUG
logging.level.com.vishwa=DEBUG

# ==================== TRACING & ZIPKIN ====================
management.tracing.enabled=true
management.tracing.sampler.probability=1.0
management.zipkin.tracing.endpoint=${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans

# ==================== ADMIN USER CONFIGURATION ====================
admin.username=${ADMIN_USERNAME:admin}
admin.email=${ADMIN_EMAIL:admin@jobapp.com}
admin.password=${ADMIN_PASSWORD}